import React, { createContext, useReducer, useContext, useEffect } from 'react';

// 1. Initial State
const initialState = {
  documents: [],
  chatMessages: [],
  currentSummary: "",
  comparisonResult: "",
  isLoading: false,
  error: null
};

// 2. Reducer
const documentReducer = (state, action) => {
  switch (action.type) {
    case 'SET_LOADING':
      return { ...state, isLoading: true, error: null };
    case 'SET_ERROR':
      return { ...state, isLoading: false, error: action.payload };
    case 'DOCS_FETCHED':
      return { ...state, isLoading: false, documents: action.payload };
    case 'DOC_UPLOADED':
      return { ...state, isLoading: false, documents: [...state.documents, action.payload] };
    case 'CHAT_MESSAGE_ADDED':
      return { ...state, isLoading: false, chatMessages: [...state.chatMessages, action.payload] };
    case 'CLEAR_CHAT':
      return { ...state, chatMessages: [] };
    case 'SUMMARY_GENERATED':
      return { ...state, isLoading: false, currentSummary: action.payload };
    default:
      return state;
  }
};

// 3. Create Context
const DocumentContext = createContext();

// 4. Provider Component
export const DocumentProvider = ({ children }) => {
  const [state, dispatch] = useReducer(documentReducer, initialState);

  // --- MOCK API FUNCTIONS ---

  // ON LOAD: Fake fetching existing documents
  useEffect(() => {
    dispatch({ type: 'SET_LOADING' });
    setTimeout(() => {
      const mockDocs = [
        { id: 'doc1', name: 'Mock_Contract_v1.pdf', status: 'indexed' },
        { id: 'doc2', name: 'NDA_Template_Final.docx', status: 'indexed' },
      ];
      dispatch({ type: 'DOCS_FETCHED', payload: mockDocs });
    }, 1000);
  }, []);

  // FAKE UPLOAD
  const uploadDocument = (file) => {
    dispatch({ type: 'SET_LOADING' });
    console.log("Simulating upload for:", file.name);
    
    setTimeout(() => {
      const newDoc = {
        id: `doc${Date.now()}`,
        name: file.name,
        status: 'indexed'
      };
      dispatch({ type: 'DOC_UPLOADED', payload: newDoc });
    }, 2000);
  };
  
  // FAKE CHATBOT
  const askQuestion = (query, documentId) => {
    dispatch({ type: 'CHAT_MESSAGE_ADDED', payload: { sender: 'user', text: query } });
    dispatch({ type: 'SET_LOADING' });
    console.log(`Simulating AI answer for: "${query}" on doc: ${documentId}`);

    setTimeout(() => {
      const aiResponse = {
        sender: 'ai',
        text: `This is a mock AI response about "${query}". The Llama 3 model (running offline) would provide a detailed answer here.`
      };
      dispatch({ type: 'CHAT_MESSAGE_ADDED', payload: aiResponse });
    }, 2500);
  };
  
  // FAKE SUMMARY
  const getSummary = async (documentId) => {
    dispatch({ type: 'SET_LOADING' });
    dispatch({ type: 'SUMMARY_GENERATED', payload: "" });
    console.log(`Simulating summary for doc: ${documentId}`);

    setTimeout(() => {
      const mockSummary = `This is a mock summary for document ${documentId}. The real summary would be generated by Llama 3 and highlight key clauses.`;
      dispatch({ type: 'SUMMARY_GENERATED', payload: mockSummary });
    }, 2000);
  };

  // Utility to clear chat
  const clearChat = () => {
    dispatch({ type: 'CLEAR_CHAT' });
  };

  return (
    <DocumentContext.Provider value={{ 
      state, 
      uploadDocument, 
      askQuestion,
      getSummary,
      clearChat 
    }}>
      {children}
    </DocumentContext.Provider>
  );
};

// 6. Custom Hook
// eslint-disable-next-line react-refresh/only-export-components
export const useDocuments = () => useContext(DocumentContext);